title: FairMeer
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "fairmeer" # the subpath of your site, e.g. /blog
url: "fairmeer.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "Fotoss/logo.png"

social: 
  name: FairMeer
  link: "https://www.facebook.com/FairMeer"


include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
